### PR TITLE
fiona / add benefits section

### PR DESCRIPTION
**Pull request by fiona-deriv**

### CODE REVIEW

**Comment by adam-deriv** [comment]
@fiona-deriv is this ready to be reviewed?

**Comment by adam-deriv** [comment]
#1

**Comment by fiona-deriv** [comment]
> @fiona-deriv is this ready to be reviewed?

yes, but I'm still working on the responsive side

**Comment by adam-deriv** [comment]
thanks for the update. Please merge and resolve conflicts when you are ready, as I see there are some

**Comment by fiona-deriv** [comment]
> thanks for the update. Please merge and resolve conflicts when you are ready, as I see there are some

done

**Review by adam-deriv — APPROVED** [review]
Thanks for the adjustments, looks good

**Pull request merged**
